name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: "*"

jobs:
    test:
        runs-on: ${{ matrix.os }}
        
        # defaults:
        #     run:
        #         shell: bash -e {0}
        # because windows runs into issues

        strategy:
            fail-fast: false
            matrix:
              # ubuntu-latest 
              # macos-latest
              os: [windows-latest]
              python: ["3.11", "3.12"]

        env:
            OS: ${{ matrix.os }}
            PYTHON: ${{ matrix.python }}

        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v6
              id: setup-uv
              with:
                  version: "latest"
                  python-version: ${{ matrix.python }}
                  enable-cache: true

            - name: Install dependencies
              run: "uv sync"

            # - name: Test
            #   env:
            #       MPLBACKEND: agg
            #       PLATFORM: ${{ matrix.os }}
            #       DISPLAY: :42
            #   run: uv run pytest --cov --color=yes --cov-report=xml

            # - name: Upload coverage to Codecov
            #   uses: codecov/codecov-action@v5
            #   with:
            #       name: coverage
            #       verbose: true
            #   env:
            #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Build Wheel
              run: "uv build"

            - name: Setup MicroMamba
              uses: mamba-org/setup-micromamba@v2
              with:
                environment-name: build_test_env
                create-args: >-
                    python=${{ matrix.python }}
                cache-downloads: true
              
            - name: Install Wheel on Windows
              if: runner.os == 'Windows'
              run: |
                $whl = Get-ChildItem -Path dist/*.whl | Select-Object -First 1
                micromamba run -n build_test_env python -m pip install $whl.FullName

            - name: Install Wheel on Linux/macOS
              if: runner.os != 'Windows'
              run: micromamba run -n build_test_env pip install dist/*.whl

            - name: Verify Installation
              run: micromamba run -n build_test_env python -c "import opendvp; print('Successfully installed and imported package into Conda environment.')"

            - name: Minimize uv cache
              run: uv cache prune --ci